<?php
$dalTablepayrolltab = array();
$dalTablepayrolltab["PtabID"] = array("type"=>3,"varname"=>"PtabID", "name" => "PtabID");
$dalTablepayrolltab["EmployeeID"] = array("type"=>3,"varname"=>"EmployeeID", "name" => "EmployeeID");
$dalTablepayrolltab["WageType"] = array("type"=>3,"varname"=>"WageType", "name" => "WageType");
$dalTablepayrolltab["Status"] = array("type"=>3,"varname"=>"Status", "name" => "Status");
$dalTablepayrolltab["BasicMonthly"] = array("type"=>5,"varname"=>"BasicMonthly", "name" => "BasicMonthly");
$dalTablepayrolltab["BasicDaily"] = array("type"=>5,"varname"=>"BasicDaily", "name" => "BasicDaily");
$dalTablepayrolltab["DWork"] = array("type"=>5,"varname"=>"DWork", "name" => "DWork");
$dalTablepayrolltab["Absent"] = array("type"=>5,"varname"=>"Absent", "name" => "Absent");
$dalTablepayrolltab["LateMins"] = array("type"=>5,"varname"=>"LateMins", "name" => "LateMins");
$dalTablepayrolltab["UndertimeMins"] = array("type"=>5,"varname"=>"UndertimeMins", "name" => "UndertimeMins");
$dalTablepayrolltab["RHolidayHrs"] = array("type"=>5,"varname"=>"RHolidayHrs", "name" => "RHolidayHrs");
$dalTablepayrolltab["SHolidayHrs"] = array("type"=>5,"varname"=>"SHolidayHrs", "name" => "SHolidayHrs");
$dalTablepayrolltab["CHolidayHrs"] = array("type"=>5,"varname"=>"CHolidayHrs", "name" => "CHolidayHrs");
$dalTablepayrolltab["ExcessHrs"] = array("type"=>5,"varname"=>"ExcessHrs", "name" => "ExcessHrs");
$dalTablepayrolltab["RegOTHrs"] = array("type"=>5,"varname"=>"RegOTHrs", "name" => "RegOTHrs");
$dalTablepayrolltab["RHOTHrs"] = array("type"=>5,"varname"=>"RHOTHrs", "name" => "RHOTHrs");
$dalTablepayrolltab["SHOTHRs"] = array("type"=>5,"varname"=>"SHOTHRs", "name" => "SHOTHRs");
$dalTablepayrolltab["CHOTHrs"] = array("type"=>5,"varname"=>"CHOTHrs", "name" => "CHOTHrs");
$dalTablepayrolltab["RDOTHrs"] = array("type"=>5,"varname"=>"RDOTHrs", "name" => "RDOTHrs");
$dalTablepayrolltab["NDHrs"] = array("type"=>5,"varname"=>"NDHrs", "name" => "NDHrs");
$dalTablepayrolltab["RDHrs"] = array("type"=>5,"varname"=>"RDHrs", "name" => "RDHrs");
$dalTablepayrolltab["RegNDHrs"] = array("type"=>5,"varname"=>"RegNDHrs", "name" => "RegNDHrs");
$dalTablepayrolltab["RHNDHrs"] = array("type"=>5,"varname"=>"RHNDHrs", "name" => "RHNDHrs");
$dalTablepayrolltab["SHNDHrs"] = array("type"=>5,"varname"=>"SHNDHrs", "name" => "SHNDHrs");
$dalTablepayrolltab["CHNDHrs"] = array("type"=>5,"varname"=>"CHNDHrs", "name" => "CHNDHrs");
$dalTablepayrolltab["RDNDHrs"] = array("type"=>5,"varname"=>"RDNDHrs", "name" => "RDNDHrs");
$dalTablepayrolltab["VLDays"] = array("type"=>5,"varname"=>"VLDays", "name" => "VLDays");
$dalTablepayrolltab["SLDays"] = array("type"=>5,"varname"=>"SLDays", "name" => "SLDays");
$dalTablepayrolltab["ELDays"] = array("type"=>5,"varname"=>"ELDays", "name" => "ELDays");
$dalTablepayrolltab["PLDays"] = array("type"=>5,"varname"=>"PLDays", "name" => "PLDays");
$dalTablepayrolltab["TrODays"] = array("type"=>5,"varname"=>"TrODays", "name" => "TrODays");
$dalTablepayrolltab["FromDate"] = array("type"=>7,"varname"=>"FromDate", "name" => "FromDate");
$dalTablepayrolltab["ToDate"] = array("type"=>7,"varname"=>"ToDate", "name" => "ToDate");
$dalTablepayrolltab["UserName"] = array("type"=>200,"varname"=>"UserName", "name" => "UserName");
$dalTablepayrolltab["AllowancePerDay"] = array("type"=>5,"varname"=>"AllowancePerDay", "name" => "AllowancePerDay");
$dalTablepayrolltab["VLBalance"] = array("type"=>5,"varname"=>"VLBalance", "name" => "VLBalance");
$dalTablepayrolltab["SLBalance"] = array("type"=>5,"varname"=>"SLBalance", "name" => "SLBalance");
$dalTablepayrolltab["ELBalance"] = array("type"=>5,"varname"=>"ELBalance", "name" => "ELBalance");
$dalTablepayrolltab["PLBalance"] = array("type"=>5,"varname"=>"PLBalance", "name" => "PLBalance");
$dalTablepayrolltab["AgencyShare"] = array("type"=>5,"varname"=>"AgencyShare", "name" => "AgencyShare");
$dalTablepayrolltab["NDMealAllowance"] = array("type"=>5,"varname"=>"NDMealAllowance", "name" => "NDMealAllowance");
$dalTablepayrolltab["Division"] = array("type"=>3,"varname"=>"Division", "name" => "Division");
$dalTablepayrolltab["Employer"] = array("type"=>3,"varname"=>"Employer", "name" => "Employer");
$dalTablepayrolltab["PayrollID"] = array("type"=>3,"varname"=>"PayrollID", "name" => "PayrollID");
$dalTablepayrolltab["Email"] = array("type"=>200,"varname"=>"Email", "name" => "Email");
$dalTablepayrolltab["Locked"] = array("type"=>16,"varname"=>"Locked", "name" => "Locked");
$dalTablepayrolltab["Position"] = array("type"=>3,"varname"=>"Position", "name" => "Position");
	$dalTablepayrolltab["PtabID"]["key"]=true;

$dal_info["payrollflex_at_localhost__payrolltab"] = &$dalTablepayrolltab;
?>