<?php
$dalTableuserinfo = array();
$dalTableuserinfo["USERID"] = array("type"=>3,"varname"=>"USERID", "name" => "USERID");
$dalTableuserinfo["Badgenumber"] = array("type"=>200,"varname"=>"Badgenumber", "name" => "Badgenumber");
$dalTableuserinfo["SSN"] = array("type"=>200,"varname"=>"SSN", "name" => "SSN");
$dalTableuserinfo["Name"] = array("type"=>200,"varname"=>"Name", "name" => "Name");
$dalTableuserinfo["Gender"] = array("type"=>200,"varname"=>"Gender", "name" => "Gender");
$dalTableuserinfo["TITLE"] = array("type"=>200,"varname"=>"TITLE", "name" => "TITLE");
$dalTableuserinfo["PAGER"] = array("type"=>200,"varname"=>"PAGER", "name" => "PAGER");
$dalTableuserinfo["BIRTHDAY"] = array("type"=>135,"varname"=>"BIRTHDAY", "name" => "BIRTHDAY");
$dalTableuserinfo["HIREDDAY"] = array("type"=>135,"varname"=>"HIREDDAY", "name" => "HIREDDAY");
$dalTableuserinfo["street"] = array("type"=>200,"varname"=>"street", "name" => "street");
$dalTableuserinfo["CITY"] = array("type"=>200,"varname"=>"CITY", "name" => "CITY");
$dalTableuserinfo["STATE"] = array("type"=>200,"varname"=>"STATE", "name" => "STATE");
$dalTableuserinfo["ZIP"] = array("type"=>200,"varname"=>"ZIP", "name" => "ZIP");
$dalTableuserinfo["OPHONE"] = array("type"=>200,"varname"=>"OPHONE", "name" => "OPHONE");
$dalTableuserinfo["FPHONE"] = array("type"=>200,"varname"=>"FPHONE", "name" => "FPHONE");
$dalTableuserinfo["VERIFICATIONMETHOD"] = array("type"=>3,"varname"=>"VERIFICATIONMETHOD", "name" => "VERIFICATIONMETHOD");
$dalTableuserinfo["DEFAULTDEPTID"] = array("type"=>3,"varname"=>"DEFAULTDEPTID", "name" => "DEFAULTDEPTID");
$dalTableuserinfo["SECURITYFLAGS"] = array("type"=>3,"varname"=>"SECURITYFLAGS", "name" => "SECURITYFLAGS");
$dalTableuserinfo["ATT"] = array("type"=>3,"varname"=>"ATT", "name" => "ATT");
$dalTableuserinfo["INLATE"] = array("type"=>3,"varname"=>"INLATE", "name" => "INLATE");
$dalTableuserinfo["OUTEARLY"] = array("type"=>3,"varname"=>"OUTEARLY", "name" => "OUTEARLY");
$dalTableuserinfo["OVERTIME"] = array("type"=>3,"varname"=>"OVERTIME", "name" => "OVERTIME");
$dalTableuserinfo["SEP"] = array("type"=>3,"varname"=>"SEP", "name" => "SEP");
$dalTableuserinfo["HOLIDAY"] = array("type"=>3,"varname"=>"HOLIDAY", "name" => "HOLIDAY");
$dalTableuserinfo["MINZU"] = array("type"=>200,"varname"=>"MINZU", "name" => "MINZU");
$dalTableuserinfo["PASSWORD"] = array("type"=>200,"varname"=>"PASSWORD", "name" => "PASSWORD");
$dalTableuserinfo["LUNCHDURATION"] = array("type"=>3,"varname"=>"LUNCHDURATION", "name" => "LUNCHDURATION");
$dalTableuserinfo["PHOTO"] = array("type"=>128,"varname"=>"PHOTO", "name" => "PHOTO");
$dalTableuserinfo["mverifypass"] = array("type"=>200,"varname"=>"mverifypass", "name" => "mverifypass");
$dalTableuserinfo["Notes"] = array("type"=>128,"varname"=>"Notes", "name" => "Notes");
$dalTableuserinfo["privilege"] = array("type"=>3,"varname"=>"privilege", "name" => "privilege");
$dalTableuserinfo["InheritDeptSch"] = array("type"=>3,"varname"=>"InheritDeptSch", "name" => "InheritDeptSch");
$dalTableuserinfo["InheritDeptSchClass"] = array("type"=>3,"varname"=>"InheritDeptSchClass", "name" => "InheritDeptSchClass");
$dalTableuserinfo["AutoSchPlan"] = array("type"=>3,"varname"=>"AutoSchPlan", "name" => "AutoSchPlan");
$dalTableuserinfo["MinAutoSchInterval"] = array("type"=>3,"varname"=>"MinAutoSchInterval", "name" => "MinAutoSchInterval");
$dalTableuserinfo["RegisterOT"] = array("type"=>3,"varname"=>"RegisterOT", "name" => "RegisterOT");
$dalTableuserinfo["InheritDeptRule"] = array("type"=>3,"varname"=>"InheritDeptRule", "name" => "InheritDeptRule");
$dalTableuserinfo["EMPRIVILEGE"] = array("type"=>3,"varname"=>"EMPRIVILEGE", "name" => "EMPRIVILEGE");
$dalTableuserinfo["CardNo"] = array("type"=>200,"varname"=>"CardNo", "name" => "CardNo");
$dalTableuserinfo["FaceGroup"] = array("type"=>3,"varname"=>"FaceGroup", "name" => "FaceGroup");
$dalTableuserinfo["AccGroup"] = array("type"=>3,"varname"=>"AccGroup", "name" => "AccGroup");
$dalTableuserinfo["UseAccGroupTZ"] = array("type"=>3,"varname"=>"UseAccGroupTZ", "name" => "UseAccGroupTZ");
$dalTableuserinfo["VerifyCode"] = array("type"=>3,"varname"=>"VerifyCode", "name" => "VerifyCode");
$dalTableuserinfo["Expires"] = array("type"=>3,"varname"=>"Expires", "name" => "Expires");
$dalTableuserinfo["ValidCount"] = array("type"=>3,"varname"=>"ValidCount", "name" => "ValidCount");
$dalTableuserinfo["ValidTimeBegin"] = array("type"=>135,"varname"=>"ValidTimeBegin", "name" => "ValidTimeBegin");
$dalTableuserinfo["ValidTimeEnd"] = array("type"=>135,"varname"=>"ValidTimeEnd", "name" => "ValidTimeEnd");
$dalTableuserinfo["TimeZone1"] = array("type"=>3,"varname"=>"TimeZone1", "name" => "TimeZone1");
$dalTableuserinfo["TimeZone2"] = array("type"=>3,"varname"=>"TimeZone2", "name" => "TimeZone2");
$dalTableuserinfo["TimeZone3"] = array("type"=>3,"varname"=>"TimeZone3", "name" => "TimeZone3");

$dal_info["payrollflex_at_localhost__userinfo"] = &$dalTableuserinfo;
?>