<?php
$dalTabledtrsummary2 = array();
$dalTabledtrsummary2["EmployeeID"] = array("type"=>3,"varname"=>"EmployeeID", "name" => "EmployeeID");
$dalTabledtrsummary2["UserName"] = array("type"=>200,"varname"=>"UserName", "name" => "UserName");
$dalTabledtrsummary2["Division"] = array("type"=>3,"varname"=>"Division", "name" => "Division");
$dalTabledtrsummary2["WageType"] = array("type"=>3,"varname"=>"WageType", "name" => "WageType");
$dalTabledtrsummary2["RegWD"] = array("type"=>14,"varname"=>"RegWD", "name" => "RegWD");
$dalTabledtrsummary2["DWork"] = array("type"=>5,"varname"=>"DWork", "name" => "DWork");
$dalTabledtrsummary2["Absent"] = array("type"=>14,"varname"=>"Absent", "name" => "Absent");
$dalTabledtrsummary2["TLates"] = array("type"=>5,"varname"=>"TLates", "name" => "TLates");
$dalTabledtrsummary2["LateMins"] = array("type"=>5,"varname"=>"LateMins", "name" => "LateMins");
$dalTabledtrsummary2["UndertimeMins"] = array("type"=>5,"varname"=>"UndertimeMins", "name" => "UndertimeMins");
$dalTabledtrsummary2["ExcessHrs"] = array("type"=>5,"varname"=>"ExcessHrs", "name" => "ExcessHrs");
$dalTabledtrsummary2["RegOTHrs"] = array("type"=>5,"varname"=>"RegOTHrs", "name" => "RegOTHrs");
$dalTabledtrsummary2["RHOTHrs"] = array("type"=>5,"varname"=>"RHOTHrs", "name" => "RHOTHrs");
$dalTabledtrsummary2["SHOTHRs"] = array("type"=>5,"varname"=>"SHOTHRs", "name" => "SHOTHRs");
$dalTabledtrsummary2["CHOTHrs"] = array("type"=>5,"varname"=>"CHOTHrs", "name" => "CHOTHrs");
$dalTabledtrsummary2["RDOTHrs"] = array("type"=>5,"varname"=>"RDOTHrs", "name" => "RDOTHrs");
$dalTabledtrsummary2["NDHrs"] = array("type"=>5,"varname"=>"NDHrs", "name" => "NDHrs");
$dalTabledtrsummary2["NDOTHrs"] = array("type"=>5,"varname"=>"NDOTHrs", "name" => "NDOTHrs");
$dalTabledtrsummary2["RDHrs"] = array("type"=>5,"varname"=>"RDHrs", "name" => "RDHrs");
$dalTabledtrsummary2["RegNDHrs"] = array("type"=>5,"varname"=>"RegNDHrs", "name" => "RegNDHrs");
$dalTabledtrsummary2["RHNDHrs"] = array("type"=>5,"varname"=>"RHNDHrs", "name" => "RHNDHrs");
$dalTabledtrsummary2["SHNDHrs"] = array("type"=>5,"varname"=>"SHNDHrs", "name" => "SHNDHrs");
$dalTabledtrsummary2["CHNDHrs"] = array("type"=>5,"varname"=>"CHNDHrs", "name" => "CHNDHrs");
$dalTabledtrsummary2["RDNDHrs"] = array("type"=>5,"varname"=>"RDNDHrs", "name" => "RDNDHrs");
$dalTabledtrsummary2["VLDays"] = array("type"=>5,"varname"=>"VLDays", "name" => "VLDays");
$dalTabledtrsummary2["SLDays"] = array("type"=>5,"varname"=>"SLDays", "name" => "SLDays");
$dalTabledtrsummary2["ELDays"] = array("type"=>5,"varname"=>"ELDays", "name" => "ELDays");
$dalTabledtrsummary2["PLDays"] = array("type"=>5,"varname"=>"PLDays", "name" => "PLDays");
$dalTabledtrsummary2["TrODays"] = array("type"=>5,"varname"=>"TrODays", "name" => "TrODays");
$dalTabledtrsummary2["RLink"] = array("type"=>3,"varname"=>"RLink", "name" => "RLink");
$dalTabledtrsummary2["NDMealAllowance"] = array("type"=>5,"varname"=>"NDMealAllowance", "name" => "NDMealAllowance");
$dalTabledtrsummary2["Employer"] = array("type"=>3,"varname"=>"Employer", "name" => "Employer");
$dalTabledtrsummary2["RHolidayHrs"] = array("type"=>5,"varname"=>"RHolidayHrs", "name" => "RHolidayHrs");
$dalTabledtrsummary2["SHolidayHrs"] = array("type"=>5,"varname"=>"SHolidayHrs", "name" => "SHolidayHrs");
$dalTabledtrsummary2["CHolidayHrs"] = array("type"=>5,"varname"=>"CHolidayHrs", "name" => "CHolidayHrs");
$dalTabledtrsummary2["TBreakLateMins"] = array("type"=>5,"varname"=>"TBreakLateMins", "name" => "TBreakLateMins");
$dalTabledtrsummary2["RegNDOTHrs"] = array("type"=>5,"varname"=>"RegNDOTHrs", "name" => "RegNDOTHrs");
$dalTabledtrsummary2["RHNDOTHrs"] = array("type"=>5,"varname"=>"RHNDOTHrs", "name" => "RHNDOTHrs");
$dalTabledtrsummary2["SHNDOTHrs"] = array("type"=>5,"varname"=>"SHNDOTHrs", "name" => "SHNDOTHrs");
$dalTabledtrsummary2["CHNDOTHrs"] = array("type"=>5,"varname"=>"CHNDOTHrs", "name" => "CHNDOTHrs");
$dalTabledtrsummary2["RDNDOTHrs"] = array("type"=>5,"varname"=>"RDNDOTHrs", "name" => "RDNDOTHrs");
$dalTabledtrsummary2["DHh"] = array("type"=>5,"varname"=>"DHh", "name" => "DHh");
$dalTabledtrsummary2["DHRDh"] = array("type"=>5,"varname"=>"DHRDh", "name" => "DHRDh");
$dalTabledtrsummary2["DHOTh"] = array("type"=>5,"varname"=>"DHOTh", "name" => "DHOTh");
$dalTabledtrsummary2["DHRDOTh"] = array("type"=>5,"varname"=>"DHRDOTh", "name" => "DHRDOTh");
$dalTabledtrsummary2["SHRDNDh"] = array("type"=>5,"varname"=>"SHRDNDh", "name" => "SHRDNDh");
$dalTabledtrsummary2["RHRDNDh"] = array("type"=>5,"varname"=>"RHRDNDh", "name" => "RHRDNDh");
$dalTabledtrsummary2["SHRDNDOTh"] = array("type"=>5,"varname"=>"SHRDNDOTh", "name" => "SHRDNDOTh");
$dalTabledtrsummary2["RHRDNDOTh"] = array("type"=>5,"varname"=>"RHRDNDOTh", "name" => "RHRDNDOTh");
$dalTabledtrsummary2["DHNDh"] = array("type"=>5,"varname"=>"DHNDh", "name" => "DHNDh");
$dalTabledtrsummary2["DHRDNDh"] = array("type"=>5,"varname"=>"DHRDNDh", "name" => "DHRDNDh");
$dalTabledtrsummary2["DHNDOTh"] = array("type"=>5,"varname"=>"DHNDOTh", "name" => "DHNDOTh");
$dalTabledtrsummary2["DHRDNDOTh"] = array("type"=>5,"varname"=>"DHRDNDOTh", "name" => "DHRDNDOTh");

$dal_info["payrollflex_at_localhost__dtrsummary2"] = &$dalTabledtrsummary2;
?>