<?php
$dalTabledtrsummary = array();
$dalTabledtrsummary["EmployeeID"] = array("type"=>3,"varname"=>"EmployeeID", "name" => "EmployeeID");
$dalTabledtrsummary["UserName"] = array("type"=>200,"varname"=>"UserName", "name" => "UserName");
$dalTabledtrsummary["Division"] = array("type"=>3,"varname"=>"Division", "name" => "Division");
$dalTabledtrsummary["WageType"] = array("type"=>3,"varname"=>"WageType", "name" => "WageType");
$dalTabledtrsummary["RegWD"] = array("type"=>14,"varname"=>"RegWD", "name" => "RegWD");
$dalTabledtrsummary["DWork"] = array("type"=>5,"varname"=>"DWork", "name" => "DWork");
$dalTabledtrsummary["Absent"] = array("type"=>14,"varname"=>"Absent", "name" => "Absent");
$dalTabledtrsummary["LateMins"] = array("type"=>5,"varname"=>"LateMins", "name" => "LateMins");
$dalTabledtrsummary["UndertimeMins"] = array("type"=>5,"varname"=>"UndertimeMins", "name" => "UndertimeMins");
$dalTabledtrsummary["ExcessHrs"] = array("type"=>5,"varname"=>"ExcessHrs", "name" => "ExcessHrs");
$dalTabledtrsummary["RegOTHrs"] = array("type"=>5,"varname"=>"RegOTHrs", "name" => "RegOTHrs");
$dalTabledtrsummary["RHOTHrs"] = array("type"=>5,"varname"=>"RHOTHrs", "name" => "RHOTHrs");
$dalTabledtrsummary["SHOTHRs"] = array("type"=>5,"varname"=>"SHOTHRs", "name" => "SHOTHRs");
$dalTabledtrsummary["CHOTHrs"] = array("type"=>5,"varname"=>"CHOTHrs", "name" => "CHOTHrs");
$dalTabledtrsummary["RDOTHrs"] = array("type"=>5,"varname"=>"RDOTHrs", "name" => "RDOTHrs");
$dalTabledtrsummary["NDHrs"] = array("type"=>14,"varname"=>"NDHrs", "name" => "NDHrs");
$dalTabledtrsummary["RDHrs"] = array("type"=>5,"varname"=>"RDHrs", "name" => "RDHrs");
$dalTabledtrsummary["RegNDHrs"] = array("type"=>5,"varname"=>"RegNDHrs", "name" => "RegNDHrs");
$dalTabledtrsummary["RegNDOTHrs"] = array("type"=>5,"varname"=>"RegNDOTHrs", "name" => "RegNDOTHrs");
$dalTabledtrsummary["RHNDHrs"] = array("type"=>5,"varname"=>"RHNDHrs", "name" => "RHNDHrs");
$dalTabledtrsummary["RHNDOTHrs"] = array("type"=>5,"varname"=>"RHNDOTHrs", "name" => "RHNDOTHrs");
$dalTabledtrsummary["SHNDHrs"] = array("type"=>5,"varname"=>"SHNDHrs", "name" => "SHNDHrs");
$dalTabledtrsummary["SHNDOTHrs"] = array("type"=>5,"varname"=>"SHNDOTHrs", "name" => "SHNDOTHrs");
$dalTabledtrsummary["CHNDHrs"] = array("type"=>5,"varname"=>"CHNDHrs", "name" => "CHNDHrs");
$dalTabledtrsummary["CHNDOTHrs"] = array("type"=>5,"varname"=>"CHNDOTHrs", "name" => "CHNDOTHrs");
$dalTabledtrsummary["RDNDHrs"] = array("type"=>5,"varname"=>"RDNDHrs", "name" => "RDNDHrs");
$dalTabledtrsummary["RDNDOTHrs"] = array("type"=>5,"varname"=>"RDNDOTHrs", "name" => "RDNDOTHrs");
$dalTabledtrsummary["VLDays"] = array("type"=>5,"varname"=>"VLDays", "name" => "VLDays");
$dalTabledtrsummary["SLDays"] = array("type"=>5,"varname"=>"SLDays", "name" => "SLDays");
$dalTabledtrsummary["ELDays"] = array("type"=>5,"varname"=>"ELDays", "name" => "ELDays");
$dalTabledtrsummary["PLDays"] = array("type"=>5,"varname"=>"PLDays", "name" => "PLDays");
$dalTabledtrsummary["TrODays"] = array("type"=>5,"varname"=>"TrODays", "name" => "TrODays");
$dalTabledtrsummary["RLink"] = array("type"=>3,"varname"=>"RLink", "name" => "RLink");
$dalTabledtrsummary["NDMealAllowance"] = array("type"=>5,"varname"=>"NDMealAllowance", "name" => "NDMealAllowance");
$dalTabledtrsummary["Employer"] = array("type"=>3,"varname"=>"Employer", "name" => "Employer");
$dalTabledtrsummary["RHolidayHrs"] = array("type"=>5,"varname"=>"RHolidayHrs", "name" => "RHolidayHrs");
$dalTabledtrsummary["SHolidayHrs"] = array("type"=>5,"varname"=>"SHolidayHrs", "name" => "SHolidayHrs");
$dalTabledtrsummary["CHolidayHrs"] = array("type"=>5,"varname"=>"CHolidayHrs", "name" => "CHolidayHrs");
$dalTabledtrsummary["TBreakLateMins"] = array("type"=>5,"varname"=>"TBreakLateMins", "name" => "TBreakLateMins");

$dal_info["payrollflex_at_localhost__dtrsummary"] = &$dalTabledtrsummary;
?>