
Runner.pages.PageSettings.addPageEvent('payroll',Runner.pages.constants.PAGE_ADD,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Create_Payroll1';if(!pageObj.buttonEventBefore['Create_Payroll1']){pageObj.buttonEventBefore['Create_Payroll1']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Create_Payroll1']){pageObj.buttonEventAfter['Create_Payroll1']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="Create_Payroll1"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Create_Payroll1"+"_"+Runner.genId();var button_Create_Payroll1=new Runner.form.Button({id:this.id,btnName:"Create_Payroll1"});button_Create_Payroll1.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('payroll',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Process_Payroll';if(!pageObj.buttonEventBefore['Process_Payroll']){pageObj.buttonEventBefore['Process_Payroll']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Requesting...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Process_Payroll']){pageObj.buttonEventAfter['Process_Payroll']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="Process_Payroll"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Process_Payroll"+"_"+Runner.genId();var button_Process_Payroll=new Runner.form.Button({id:this.id,btnName:"Process_Payroll"});button_Process_Payroll.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('payroll',Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){var ctrlst=Runner.getControl(pageid,'Statutories');var ctrlss=Runner.getControl(pageid,'SSS');var ctrlpi=Runner.getControl(pageid,'PagIbig');var ctrlph=Runner.getControl(pageid,'PhilHealth');function func1(){if(ctrlst.getValue()=='on'){ctrlss.setValue(1);ctrlpi.setValue(1);ctrlph.setValue(1);}
else{ctrlss.clear();ctrlpi.clear();ctrlph.clear();}};function func2(){if(ctrlss.getValue()=='on'||ctrlpi.getValue()=='on'||ctrlph.getValue()=='on'){ctrlst.setValue(1);}
if(ctrlss.getValue()!='on'&ctrlpi.getValue()!='on'&ctrlph.getValue()!='on'){ctrlst.clear();}};ctrlst.on('change',func1);ctrlss.on('change',func2);ctrlpi.on('change',func2);ctrlph.on('change',func2);;});