
Runner.pages.PageSettings.addPageEvent('demo_user11',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Update_SSS1';if(!pageObj.buttonEventBefore['Update_SSS1']){pageObj.buttonEventBefore['Update_SSS1']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Updating...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Update_SSS1']){pageObj.buttonEventAfter['Update_SSS1']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="Update_SSS1"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Update_SSS1"+"_"+Runner.genId();var button_Update_SSS1=new Runner.form.Button({id:this.id,btnName:"Update_SSS1"});button_Update_SSS1.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('demo_user11',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Update_PhilHelath1';if(!pageObj.buttonEventBefore['Update_PhilHelath1']){pageObj.buttonEventBefore['Update_PhilHelath1']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Updating...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Update_PhilHelath1']){pageObj.buttonEventAfter['Update_PhilHelath1']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="Update_PhilHelath1"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Update_PhilHelath1"+"_"+Runner.genId();var button_Update_PhilHelath1=new Runner.form.Button({id:this.id,btnName:"Update_PhilHelath1"});button_Update_PhilHelath1.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('demo_user11',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Update_Pag_Ibig21';if(!pageObj.buttonEventBefore['Update_Pag_Ibig21']){pageObj.buttonEventBefore['Update_Pag_Ibig21']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Updating...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Update_Pag_Ibig21']){pageObj.buttonEventAfter['Update_Pag_Ibig21']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="Update_Pag_Ibig21"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Update_Pag_Ibig21"+"_"+Runner.genId();var button_Update_Pag_Ibig21=new Runner.form.Button({id:this.id,btnName:"Update_Pag_Ibig21"});button_Update_Pag_Ibig21.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('demo_user11',Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){var ctrlap1=Runner.getControl(pageid,'Approved');var ctrlad1=Runner.getControl(pageid,'ApprovedDate');var ctrlapb1=Runner.getControl(pageid,'Approvedby');var ctrlck1=Runner.getControl(pageid,'Checked');var ctrlckd1=Runner.getControl(pageid,'CheckedDate');var ctrlckb1=Runner.getControl(pageid,'Checkedby');var ctrlina=Runner.getControl(pageid,'Inactive');ctrlina.makeReadonly();var apuser=proxy.approvalpress;ctrlad1.makeReadonly();ctrlckd1.makeReadonly();d1=new Date();var nd=d1.toLocaleDateString();function funcax(){if(ctrlap1.getValue()=='on'){ctrlad1.setValue(d1);ctrlapb1.setValue(apuser);};if(ctrlap1.getValue()==''){ctrlad1.setValue('');ctrlapb1.setValue('');};};function funcay(){if(ctrlck1.getValue()=='on'){ctrlckd1.setValue(d1);ctrlckb1.setValue(apuser);};if(ctrlck1.getValue()==''){ctrlckd1.setValue('');ctrlckb1.setValue('');};};ctrlap1.on('onchange',funcax);ctrlck1.on('onchange',funcay);});Runner.pages.PageSettings.addPageEvent('demo_user11',Runner.pages.constants.PAGE_ADD,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){var ctrlprep1=Runner.getControl(pageid,'Preparedby');;});Runner.pages.PageSettings.addPageEvent('demo_user11',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){var s1=proxy.sss;var p1=proxy.phil;var p2=proxy.pag;if(p1==1){var id="Update_PhilHelath";var button=$("[id^="+id+"]");Runner.addDisabledClass(button);};if(p1!=1){var id="Update_PhilHelath";var button=$("[id^="+id+"]");Runner.delDisabledClass(button);};if(p2==1){var id="Update_Pag_Ibig2";var button=$("[id^="+id+"]");Runner.addDisabledClass(button);};if(p2!=1){var id="Update_Pag_Ibig2";var button=$("[id^="+id+"]");Runner.delDisabledClass(button);};if(s1==1){var id="Update_SSS";var button=$("[id^="+id+"]");Runner.addDisabledClass(button);};if(s1!=1){var id="Update_SSS";var button=$("[id^="+id+"]");Runner.delDisabledClass(button);};;});