
Runner.pages.PageSettings.addPageEvent('ssscontsummary',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='SSS_Contribution';if(!pageObj.buttonEventBefore['SSS_Contribution']){pageObj.buttonEventBefore['SSS_Contribution']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Preview...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['SSS_Contribution']){pageObj.buttonEventAfter['SSS_Contribution']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var e1=result["Employer"];var dt=result["FromDate"];var dt1=result["ToDate"];var pr1=result["PreparedBy"];window.open('pdfprint2/ssscont.php?ps1='+dt1+'&em1='+e1+'&prp1='+pr1+'&dt2='+dt,'_blank');}}
$('a[id="SSS_Contribution"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="SSS_Contribution"+"_"+Runner.genId();var button_SSS_Contribution=new Runner.form.Button({id:this.id,btnName:"SSS_Contribution"});button_SSS_Contribution.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('ssscontsummary',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Pag_Ibig_Contribution1';if(!pageObj.buttonEventBefore['Pag_Ibig_Contribution1']){pageObj.buttonEventBefore['Pag_Ibig_Contribution1']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Preview...";ctrl.setMessage("Preview...");}}
if(!pageObj.buttonEventAfter['Pag_Ibig_Contribution1']){pageObj.buttonEventAfter['Pag_Ibig_Contribution1']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var q=result["PSID"];var e1=result["Employer"];var dt=result["FromDate"];var dt1=result["ToDate"];var pr1=result["PreparedBy"];window.open('pdfprint2/pagcont.php?ps1='+dt1+'&em1='+e1+'&prp1='+pr1+'&dt2='+dt,'_blank');}}
$('a[id="Pag_Ibig_Contribution1"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Pag_Ibig_Contribution1"+"_"+Runner.genId();var button_Pag_Ibig_Contribution1=new Runner.form.Button({id:this.id,btnName:"Pag_Ibig_Contribution1"});button_Pag_Ibig_Contribution1.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('ssscontsummary',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='PhilHealth';if(!pageObj.buttonEventBefore['PhilHealth']){pageObj.buttonEventBefore['PhilHealth']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Preview...";ctrl.setMessage("Preview...");}}
if(!pageObj.buttonEventAfter['PhilHealth']){pageObj.buttonEventAfter['PhilHealth']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var q=result["PSID"];var e1=result["Employer"];var dt=result["FromDate"];var dt1=result["ToDate"];var pr1=result["PreparedBy"];window.open('pdfprint2/philcont.php?ps1='+dt1+'&em1='+e1+'&prp1='+pr1+'&dt2='+dt,'_blank');}}
$('a[id="PhilHealth"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="PhilHealth"+"_"+Runner.genId();var button_PhilHealth=new Runner.form.Button({id:this.id,btnName:"PhilHealth"});button_PhilHealth.init({args:[pageObj,proxy,pageid]});});});