
Runner.pages.PageSettings.addPageEvent('payrolldiv',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Payslip';if(!pageObj.buttonEventBefore['Payslip']){pageObj.buttonEventBefore['Payslip']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Previewing...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Payslip']){pageObj.buttonEventAfter['Payslip']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var q=result["PSID"];var q2=result["PRollID"];var e1=result["Employer"];var dt=result["ToDate"];window.open('pdfprint2/payslipgroup.php?ps1='+dt+'&em1='+e1,'_blank');}}
$('a[id="Payslip"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Payslip"+"_"+Runner.genId();var button_Payslip=new Runner.form.Button({id:this.id,btnName:"Payslip"});button_Payslip.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('payrolldiv',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Bank_Registry';if(!pageObj.buttonEventBefore['Bank_Registry']){pageObj.buttonEventBefore['Bank_Registry']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Previewing...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Bank_Registry']){pageObj.buttonEventAfter['Bank_Registry']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var q=result["PSID"];var q2=result["PRollID"];var e1=result["Employer"];var dt1=result["ToDate"];window.open('pdfprint2/psummary3.php?ps1='+dt1+'&em1='+e1,'_blank');}}
$('a[id="Bank_Registry"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Bank_Registry"+"_"+Runner.genId();var button_Bank_Registry=new Runner.form.Button({id:this.id,btnName:"Bank_Registry"});button_Bank_Registry.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('payrolldiv',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Summary_A';if(!pageObj.buttonEventBefore['Summary_A']){pageObj.buttonEventBefore['Summary_A']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Previewing...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Summary_A']){pageObj.buttonEventAfter['Summary_A']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var q=result["PSID"];var q2=result["PRollID"];var e1=result["Employer"];var dt1=result["ToDate"];window.open('pdfprint2/psummary.php?ps1='+dt1+'&em1='+e1,'_blank');}}
$('a[id="Summary_A"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Summary_A"+"_"+Runner.genId();var button_Summary_A=new Runner.form.Button({id:this.id,btnName:"Summary_A"});button_Summary_A.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('payrolldiv',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Summary_B';if(!pageObj.buttonEventBefore['Summary_B']){pageObj.buttonEventBefore['Summary_B']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Previewing...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Summary_B']){pageObj.buttonEventAfter['Summary_B']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var q=result["PSID"];var q2=result["PRollID"];var e1=result["Employer"];var dt1=result["ToDate"];window.open('pdfprint2/psummary2.php?ps1='+dt1+'&em1='+e1,'_blank');}}
$('a[id="Summary_B"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Summary_B"+"_"+Runner.genId();var button_Summary_B=new Runner.form.Button({id:this.id,btnName:"Summary_B"});button_Summary_B.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('payrolldiv',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Summary_C';if(!pageObj.buttonEventBefore['Summary_C']){pageObj.buttonEventBefore['Summary_C']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Previewing...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Summary_C']){pageObj.buttonEventAfter['Summary_C']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var q=result["PSID"];var q2=result["PRollID"];var e1=result["Employer"];var dt1=result["ToDate"];window.open('pdfprint2/psummary22.php?ps1='+dt1+'&em1='+e1,'_blank');}}
$('a[id="Summary_C"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Summary_C"+"_"+Runner.genId();var button_Summary_C=new Runner.form.Button({id:this.id,btnName:"Summary_C"});button_Summary_C.init({args:[pageObj,proxy,pageid]});});});