
Runner.pages.PageSettings.addPageEvent('payrolldiv',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Payslip';if(!pageObj.buttonEventBefore['Payslip']){pageObj.buttonEventBefore['Payslip']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Previewing...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Payslip']){pageObj.buttonEventAfter['Payslip']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var q=result["PSID"];var q2=result["PRollID"];var d1=result["Division"];var e1=result["Employer"];var w1=result["WageType"];var dt=result["ToDate"];window.open('pdfprint2/payslipgroup.php?ps1='+dt+'&dv1='+d1+'&em1='+e1+'&wt1='+w1,'_blank');}}
$('a[id="Payslip"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Payslip"+"_"+Runner.genId();var button_Payslip=new Runner.form.Button({id:this.id,btnName:"Payslip"});button_Payslip.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('payrolldiv',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Bank_Registry';if(!pageObj.buttonEventBefore['Bank_Registry']){pageObj.buttonEventBefore['Bank_Registry']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Previewing...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Bank_Registry']){pageObj.buttonEventAfter['Bank_Registry']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var q=result["PSID"];var q2=result["PRollID"];var d1=result["Division"];var e1=result["Employer"];var w1=result["WageType"];var dt1=result["ToDate"];window.open('pdfprint2/psummary3.php?ps1='+dt1+'&dv1='+d1+'&em1='+e1+'&wt1='+w1,'_blank');}}
$('a[id="Bank_Registry"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Bank_Registry"+"_"+Runner.genId();var button_Bank_Registry=new Runner.form.Button({id:this.id,btnName:"Bank_Registry"});button_Bank_Registry.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('payrolldiv',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Summary_A';if(!pageObj.buttonEventBefore['Summary_A']){pageObj.buttonEventBefore['Summary_A']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Previewing...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Summary_A']){pageObj.buttonEventAfter['Summary_A']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var q=result["PSID"];var q2=result["PRollID"];var d1=result["Division"];var e1=result["Employer"];var w1=result["WageType"];var dt1=result["ToDate"];window.open('pdfprint2/psummary.php?ps1='+dt1+'&dv1='+d1+'&em1='+e1+'&wt1='+w1,'_blank');}}
$('a[id="Summary_A"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Summary_A"+"_"+Runner.genId();var button_Summary_A=new Runner.form.Button({id:this.id,btnName:"Summary_A"});button_Summary_A.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('payrolldiv',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Summary_B';if(!pageObj.buttonEventBefore['Summary_B']){pageObj.buttonEventBefore['Summary_B']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Previewing...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Summary_B']){pageObj.buttonEventAfter['Summary_B']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var q=result["PSID"];var q2=result["PRollID"];var d1=result["Division"];var e1=result["Employer"];var w1=result["WageType"];var dt1=result["ToDate"];window.open('pdfprint2/psummary2.php?ps1='+dt1+'&dv1='+d1+'&em1='+e1+'&wt1='+w1,'_blank');}}
$('a[id="Summary_B"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Summary_B"+"_"+Runner.genId();var button_Summary_B=new Runner.form.Button({id:this.id,btnName:"Summary_B"});button_Summary_B.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('payrolldiv',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Summary_C';if(!pageObj.buttonEventBefore['Summary_C']){pageObj.buttonEventBefore['Summary_C']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Previewing...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Summary_C']){pageObj.buttonEventAfter['Summary_C']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var q=result["PSID"];var q2=result["PRollID"];var d1=result["Division"];var e1=result["Employer"];var w1=result["WageType"];var dt1=result["ToDate"];window.open('pdfprint2/psummary22.php?ps1='+dt1+'&dv1='+d1+'&em1='+e1+'&wt1='+w1,'_blank');}}
$('a[id="Summary_C"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Summary_C"+"_"+Runner.genId();var button_Summary_C=new Runner.form.Button({id:this.id,btnName:"Summary_C"});button_Summary_C.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('payrolldiv',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Upload_Payslips';if(!pageObj.buttonEventBefore['Upload_Payslips']){pageObj.buttonEventBefore['Upload_Payslips']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Uploading...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Upload_Payslips']){pageObj.buttonEventAfter['Upload_Payslips']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+"";ctrl.setMessage(message);}}
$('a[id="Upload_Payslips"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Upload_Payslips"+"_"+Runner.genId();var button_Upload_Payslips=new Runner.form.Button({id:this.id,btnName:"Upload_Payslips"});button_Upload_Payslips.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('payrolldiv',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Clear_Uploaded_Payslips';if(!pageObj.buttonEventBefore['Clear_Uploaded_Payslips']){pageObj.buttonEventBefore['Clear_Uploaded_Payslips']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Deleting...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Clear_Uploaded_Payslips']){pageObj.buttonEventAfter['Clear_Uploaded_Payslips']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+"";ctrl.setMessage(message);}}
$('a[id="Clear_Uploaded_Payslips"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Clear_Uploaded_Payslips"+"_"+Runner.genId();var button_Clear_Uploaded_Payslips=new Runner.form.Button({id:this.id,btnName:"Clear_Uploaded_Payslips"});button_Clear_Uploaded_Payslips.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('payrolldiv',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Payslip5';if(!pageObj.buttonEventBefore['Payslip5']){pageObj.buttonEventBefore['Payslip5']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Printing...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Payslip5']){pageObj.buttonEventAfter['Payslip5']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var q=result["PSID"];var q2=result["PRollID"];var d1=result["Division"];var e1=result["Employer"];var w1=result["WageType"];var dt=result["ToDate"];window.open('pdfprint2/payslipgroupup.php?ps1='+dt+'&dv1='+d1+'&em1='+e1+'&wt1='+w1,'_blank');}}
$('a[id="Payslip5"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Payslip5"+"_"+Runner.genId();var button_Payslip5=new Runner.form.Button({id:this.id,btnName:"Payslip5"});button_Payslip5.init({args:[pageObj,proxy,pageid]});});});