
Runner.pages.PageSettings.addPageEvent('dtrrange',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Process_DTR2';if(!pageObj.buttonEventBefore['Process_DTR2']){pageObj.buttonEventBefore['Process_DTR2']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Processing...";ctrl.setMessage("Processing...");}}
if(!pageObj.buttonEventAfter['Process_DTR2']){pageObj.buttonEventAfter['Process_DTR2']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="Process_DTR2"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Process_DTR2"+"_"+Runner.genId();var button_Process_DTR2=new Runner.form.Button({id:this.id,btnName:"Process_DTR2"});button_Process_DTR2.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('dtrrange',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Upload_DTR_to_Payroll2';if(!pageObj.buttonEventBefore['Upload_DTR_to_Payroll2']){pageObj.buttonEventBefore['Upload_DTR_to_Payroll2']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Uploading...";ctrl.setMessage("Processing...");}}
if(!pageObj.buttonEventAfter['Upload_DTR_to_Payroll2']){pageObj.buttonEventAfter['Upload_DTR_to_Payroll2']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="Upload_DTR_to_Payroll2"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Upload_DTR_to_Payroll2"+"_"+Runner.genId();var button_Upload_DTR_to_Payroll2=new Runner.form.Button({id:this.id,btnName:"Upload_DTR_to_Payroll2"});button_Upload_DTR_to_Payroll2.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('dtrrange',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Create_Payroll';if(!pageObj.buttonEventBefore['Create_Payroll']){pageObj.buttonEventBefore['Create_Payroll']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Creating Payroll...";ctrl.setMessage("Processing...");}}
if(!pageObj.buttonEventAfter['Create_Payroll']){pageObj.buttonEventAfter['Create_Payroll']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="Create_Payroll"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Create_Payroll"+"_"+Runner.genId();var button_Create_Payroll=new Runner.form.Button({id:this.id,btnName:"Create_Payroll"});button_Create_Payroll.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('dtrrange',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Update_Payroll3';if(!pageObj.buttonEventBefore['Update_Payroll3']){pageObj.buttonEventBefore['Update_Payroll3']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Updating...";ctrl.setMessage("Processing...");}}
if(!pageObj.buttonEventAfter['Update_Payroll3']){pageObj.buttonEventAfter['Update_Payroll3']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="Update_Payroll3"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Update_Payroll3"+"_"+Runner.genId();var button_Update_Payroll3=new Runner.form.Button({id:this.id,btnName:"Update_Payroll3"});button_Update_Payroll3.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('dtrrange',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Clear_Payroll1';if(!pageObj.buttonEventBefore['Clear_Payroll1']){pageObj.buttonEventBefore['Clear_Payroll1']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){var txt;var r=confirm("You're about to delete this payroll range. Are you sure?");if(r==true){params["txt"]="Deleting data...";ctrl.setMessage("Processing...");}else{txt="You pressed Cancel!";return false;}}}
if(!pageObj.buttonEventAfter['Clear_Payroll1']){pageObj.buttonEventAfter['Clear_Payroll1']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="Clear_Payroll1"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Clear_Payroll1"+"_"+Runner.genId();var button_Clear_Payroll1=new Runner.form.Button({id:this.id,btnName:"Clear_Payroll1"});button_Clear_Payroll1.init({args:[pageObj,proxy,pageid]});});});