
Runner.pages.PageSettings.addPageEvent('dtrrange1',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Process_DTR21';if(!pageObj.buttonEventBefore['Process_DTR21']){pageObj.buttonEventBefore['Process_DTR21']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Processing...";ctrl.setMessage("Processing...");}}
if(!pageObj.buttonEventAfter['Process_DTR21']){pageObj.buttonEventAfter['Process_DTR21']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="Process_DTR21"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Process_DTR21"+"_"+Runner.genId();var button_Process_DTR21=new Runner.form.Button({id:this.id,btnName:"Process_DTR21"});button_Process_DTR21.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('dtrrange1',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Approved_OT_ND_RD1';if(!pageObj.buttonEventBefore['Approved_OT_ND_RD1']){pageObj.buttonEventBefore['Approved_OT_ND_RD1']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Connecting...";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Approved_OT_ND_RD1']){pageObj.buttonEventAfter['Approved_OT_ND_RD1']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){window.location.href="otndrdglobal1_list.php";}}
$('a[id="Approved_OT_ND_RD1"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Approved_OT_ND_RD1"+"_"+Runner.genId();var button_Approved_OT_ND_RD1=new Runner.form.Button({id:this.id,btnName:"Approved_OT_ND_RD1"});button_Approved_OT_ND_RD1.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('dtrrange1',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Upload_DTR_to_Payroll21';if(!pageObj.buttonEventBefore['Upload_DTR_to_Payroll21']){pageObj.buttonEventBefore['Upload_DTR_to_Payroll21']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Uploading...";ctrl.setMessage("Processing...");}}
if(!pageObj.buttonEventAfter['Upload_DTR_to_Payroll21']){pageObj.buttonEventAfter['Upload_DTR_to_Payroll21']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="Upload_DTR_to_Payroll21"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Upload_DTR_to_Payroll21"+"_"+Runner.genId();var button_Upload_DTR_to_Payroll21=new Runner.form.Button({id:this.id,btnName:"Upload_DTR_to_Payroll21"});button_Upload_DTR_to_Payroll21.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent('dtrrange1',Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Update_Payroll31';if(!pageObj.buttonEventBefore['Update_Payroll31']){pageObj.buttonEventBefore['Update_Payroll31']=function(params,ctrl,pageObj,proxy,pageid,rowData,row){params["txt"]="Updating...";ctrl.setMessage("Processing...");}}
if(!pageObj.buttonEventAfter['Update_Payroll31']){pageObj.buttonEventAfter['Update_Payroll31']=function(result,ctrl,pageObj,proxy,pageid,rowData,row){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id="Update_Payroll31"]').each(function(){if($(this).closest('.gridRowAdd').length){return;}
this.id="Update_Payroll31"+"_"+Runner.genId();var button_Update_Payroll31=new Runner.form.Button({id:this.id,btnName:"Update_Payroll31"});button_Update_Payroll31.init({args:[pageObj,proxy,pageid]});});});